import { hex } from "../lib/color.mjs";

export const meta = { app: "vscode", name: "VS Code", category: "editor", ext: "json" };

export default function vscode(v, m) {
  const { ui: u, ansi: a, syntax: s } = v;
  const name = `${m.name} ${v.appearance === "dark" ? "Dark" : "Light"}`;
  const tc = (scope, foreground, fontStyle) => ({
    scope,
    settings: fontStyle ? { foreground: hex(foreground), fontStyle } : { foreground: hex(foreground) },
  });

  const theme = {
    name,
    type: v.appearance,
    semanticHighlighting: true,
    colors: {
      "focusBorder": hex(u.accent),
      "foreground": hex(u.fg),
      "selection.background": hex(u.selection),
      "errorForeground": hex(v.extra.error),
      // editor
      "editor.background": hex(u.bg),
      "editor.foreground": hex(u.fg),
      "editorLineNumber.foreground": hex(u.comment),
      "editorLineNumber.activeForeground": hex(u.fg),
      "editor.lineHighlightBackground": hex(u.bgHl),
      "editor.selectionBackground": hex(u.selection),
      "editor.selectionHighlightBackground": hex(u.bgHl),
      "editor.wordHighlightBackground": hex(u.bgHl),
      "editor.findMatchHighlightBackground": hex(u.selection),
      "editorCursor.foreground": hex(u.cursor),
      "editorWhitespace.foreground": hex(u.border),
      "editorIndentGuide.background1": hex(u.border),
      "editorIndentGuide.activeBackground1": hex(u.comment),
      "editorBracketMatch.background": hex(u.bgHl),
      "editorBracketMatch.border": hex(u.accent),
      // gutter / widgets
      "editorWidget.background": hex(u.bgAlt),
      "editorWidget.border": hex(u.border),
      "editorHoverWidget.background": hex(u.bgAlt),
      "editorHoverWidget.border": hex(u.border),
      "editorSuggestWidget.background": hex(u.bgAlt),
      "editorSuggestWidget.selectedBackground": hex(u.bgHl),
      // workbench chrome
      "activityBar.background": hex(u.bgAlt),
      "activityBar.foreground": hex(u.fg),
      "activityBar.inactiveForeground": hex(u.comment),
      "activityBarBadge.background": hex(u.accent),
      "activityBarBadge.foreground": "#ffffff",
      "sideBar.background": hex(u.bgAlt),
      "sideBar.foreground": hex(u.fgDim),
      "sideBar.border": hex(u.border),
      "sideBarSectionHeader.background": hex(u.bg),
      "sideBarTitle.foreground": hex(u.fg),
      "list.activeSelectionBackground": hex(u.bgHl),
      "list.activeSelectionForeground": hex(u.fg),
      "list.hoverBackground": hex(u.bgHl),
      "list.highlightForeground": hex(u.accent),
      "tab.activeBackground": hex(u.bg),
      "tab.inactiveBackground": hex(u.bgAlt),
      "tab.activeForeground": hex(u.fg),
      "tab.inactiveForeground": hex(u.comment),
      "tab.activeBorderTop": hex(u.accent),
      "tab.border": hex(u.border),
      "editorGroupHeader.tabsBackground": hex(u.bgAlt),
      "titleBar.activeBackground": hex(u.bgAlt),
      "titleBar.activeForeground": hex(u.fg),
      "titleBar.inactiveBackground": hex(u.bgAlt),
      "statusBar.background": hex(u.bgAlt),
      "statusBar.foreground": hex(u.fgDim),
      "statusBar.border": hex(u.border),
      "statusBar.noFolderBackground": hex(u.bgAlt),
      "statusBar.debuggingBackground": hex(u.accent),
      "statusBarItem.remoteBackground": hex(u.accent),
      "panel.background": hex(u.bg),
      "panel.border": hex(u.border),
      "panelTitle.activeForeground": hex(u.fg),
      "panelTitle.activeBorder": hex(u.accent),
      // inputs / buttons
      "input.background": hex(u.bg),
      "input.foreground": hex(u.fg),
      "input.border": hex(u.border),
      "input.placeholderForeground": hex(u.comment),
      "button.background": hex(u.accent),
      "button.foreground": "#ffffff",
      "button.hoverBackground": hex(v.extra.orange),
      "badge.background": hex(u.accent),
      "badge.foreground": "#ffffff",
      "progressBar.background": hex(u.accent),
      "scrollbarSlider.background": hex(u.border),
      "scrollbarSlider.hoverBackground": hex(u.comment),
      "scrollbarSlider.activeBackground": hex(u.comment),
      // git decorations
      "gitDecoration.modifiedResourceForeground": hex(v.extra.warning),
      "gitDecoration.deletedResourceForeground": hex(v.extra.error),
      "gitDecoration.untrackedResourceForeground": hex(v.extra.success),
      "gitDecoration.ignoredResourceForeground": hex(u.comment),
      "editorError.foreground": hex(v.extra.error),
      "editorWarning.foreground": hex(v.extra.warning),
      "editorInfo.foreground": hex(v.extra.info),
      // integrated terminal — the 16 ANSI colors
      "terminal.background": hex(u.bg),
      "terminal.foreground": hex(u.fg),
      "terminalCursor.foreground": hex(u.cursor),
      "terminal.ansiBlack": hex(a.black),
      "terminal.ansiRed": hex(a.red),
      "terminal.ansiGreen": hex(a.green),
      "terminal.ansiYellow": hex(a.yellow),
      "terminal.ansiBlue": hex(a.blue),
      "terminal.ansiMagenta": hex(a.magenta),
      "terminal.ansiCyan": hex(a.cyan),
      "terminal.ansiWhite": hex(a.white),
      "terminal.ansiBrightBlack": hex(a.brightBlack),
      "terminal.ansiBrightRed": hex(a.brightRed),
      "terminal.ansiBrightGreen": hex(a.brightGreen),
      "terminal.ansiBrightYellow": hex(a.brightYellow),
      "terminal.ansiBrightBlue": hex(a.brightBlue),
      "terminal.ansiBrightMagenta": hex(a.brightMagenta),
      "terminal.ansiBrightCyan": hex(a.brightCyan),
      "terminal.ansiBrightWhite": hex(a.brightWhite),
    },
    tokenColors: [
      tc(["comment", "punctuation.definition.comment"], s.comment, "italic"),
      tc(["string", "string.quoted", "constant.other.symbol"], s.string),
      tc(["string.regexp"], s.regex),
      tc(["constant.character.escape"], s.escape),
      tc(["constant.numeric", "constant.language.boolean", "constant.language.null"], s.number),
      tc(["constant.language", "constant.other"], s.constant),
      tc(["keyword", "storage.type", "storage.modifier", "keyword.control"], s.keyword),
      tc(["keyword.operator"], s.operator),
      tc(["variable", "variable.other", "meta.definition.variable.name"], s.variable),
      tc(["variable.parameter"], s.variable, "italic"),
      tc(["entity.name.function", "support.function", "meta.function-call.generic"], s.function),
      tc(["entity.name.type", "entity.name.class", "support.type", "support.class"], s.type),
      tc(["entity.name.tag"], s.tag),
      tc(["entity.other.attribute-name"], s.attribute),
      tc(["support.type.property-name", "meta.object-literal.key"], s.property),
      tc(["punctuation", "meta.brace", "meta.delimiter"], s.punctuation),
      tc(["markup.heading", "markup.heading entity.name"], s.keyword, "bold"),
      tc(["markup.bold"], s.constant, "bold"),
      tc(["markup.italic"], s.string, "italic"),
      tc(["markup.inline.raw", "markup.fenced_code"], s.string),
      tc(["invalid", "invalid.illegal"], s.invalid),
    ],
  };
  return JSON.stringify(theme, null, 2) + "\n";
}
