import { hex, rgbaCss } from "../lib/color.mjs";

export const meta = { app: "zed", name: "Zed", category: "editor", ext: "json" };

export default function zed(v, m) {
  const { ui: u, ansi: a, syntax: s, extra: e } = v;
  const sy = (color, font_style) => (font_style ? { color: hex(color), font_style } : { color: hex(color) });

  const theme = {
    name: `${m.name} ${v.appearance === "dark" ? "Dark" : "Light"}`,
    appearance: v.appearance,
    style: {
      "background": hex(u.bg),
      "border": hex(u.border),
      "border.variant": hex(u.border),
      "elevated_surface.background": hex(u.bgAlt),
      "surface.background": hex(u.bgAlt),
      "element.background": hex(u.bgAlt),
      "element.hover": hex(u.bgHl),
      "element.selected": hex(u.bgHl),
      "ghost_element.hover": hex(u.bgHl),
      "text": hex(u.fg),
      "text.muted": hex(u.fgDim),
      "text.placeholder": hex(u.comment),
      "text.disabled": hex(u.comment),
      "text.accent": hex(u.accent),
      "icon": hex(u.fgDim),
      "icon.accent": hex(u.accent),
      "status_bar.background": hex(u.bgAlt),
      "title_bar.background": hex(u.bgAlt),
      "toolbar.background": hex(u.bg),
      "tab_bar.background": hex(u.bgAlt),
      "tab.active_background": hex(u.bg),
      "tab.inactive_background": hex(u.bgAlt),
      "editor.background": hex(u.bg),
      "editor.foreground": hex(u.fg),
      "editor.gutter.background": hex(u.bg),
      "editor.line_number": hex(u.comment),
      "editor.active_line_number": hex(u.fg),
      "editor.active_line.background": hex(u.bgHl),
      "editor.highlighted_line.background": hex(u.bgHl),
      "editor.document_highlight.read_background": rgbaCss(u.selection, 0.5),
      "scrollbar.thumb.background": rgbaCss(u.comment, 0.4),
      "element.active": hex(u.bgHl),
      "drop_target.background": rgbaCss(u.accent, 0.2),
      "players": [{ cursor: hex(u.cursor), background: hex(u.accent), selection: rgbaCss(u.selection, 0.6) }],
      "error": hex(e.error),
      "warning": hex(e.warning),
      "info": hex(e.info),
      "success": hex(e.success),
      "terminal.background": hex(u.bg),
      "terminal.foreground": hex(u.fg),
      "terminal.ansi.black": hex(a.black),
      "terminal.ansi.red": hex(a.red),
      "terminal.ansi.green": hex(a.green),
      "terminal.ansi.yellow": hex(a.yellow),
      "terminal.ansi.blue": hex(a.blue),
      "terminal.ansi.magenta": hex(a.magenta),
      "terminal.ansi.cyan": hex(a.cyan),
      "terminal.ansi.white": hex(a.white),
      "terminal.ansi.bright_black": hex(a.brightBlack),
      "terminal.ansi.bright_red": hex(a.brightRed),
      "terminal.ansi.bright_green": hex(a.brightGreen),
      "terminal.ansi.bright_yellow": hex(a.brightYellow),
      "terminal.ansi.bright_blue": hex(a.brightBlue),
      "terminal.ansi.bright_magenta": hex(a.brightMagenta),
      "terminal.ansi.bright_cyan": hex(a.brightCyan),
      "terminal.ansi.bright_white": hex(a.brightWhite),
      "syntax": {
        "comment": sy(s.comment, "italic"),
        "string": sy(s.string),
        "string.escape": sy(s.escape),
        "string.regex": sy(s.regex),
        "number": sy(s.number),
        "boolean": sy(s.constant),
        "constant": sy(s.constant),
        "keyword": sy(s.keyword),
        "operator": sy(s.operator),
        "function": sy(s.function),
        "function.method": sy(s.function),
        "type": sy(s.type),
        "variable": sy(s.variable),
        "property": sy(s.property),
        "attribute": sy(s.attribute),
        "tag": sy(s.tag),
        "punctuation": sy(s.punctuation),
        "punctuation.bracket": sy(s.punctuation),
        "title": sy(s.keyword, "bold"),
        "emphasis": sy(s.string, "italic"),
      },
    },
  };

  return JSON.stringify(
    {
      $schema: "https://zed.dev/schema/themes/v0.2.0.json",
      name: `${m.name} — Sabotage (${v.appearance})`,
      author: m.author,
      themes: [theme],
    },
    null,
    2,
  ) + "\n";
}
